apiVersion: apps/v1
kind: Deployment
metadata:
  name: etudiants-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etudiants
  template:
    metadata:
      labels:
        app: etudiants
    spec:
      containers:
        - name: etudiants-container
          image: tynaz02/etudiants-service:Version1
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: etudiants-service
spec:
  selector:
    app: etudiants
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort