apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
        - name: notes-container
          image: tynaz02/notes-service:Version4
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: postgresql://rsa_user:rsa_pass@postgresql-service:5432/rsa_db  

---

apiVersion: v1
kind: Service
metadata:
  name: notes-service
spec:
  selector:
    app: notes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
