
name: CI - Docker Flask Build

on:
  pull_request:

jobs:
  build-notes-service:
    runs-on: ubuntu-latest
    name: Build Flask Image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (notes-service)
        working-directory: backend/notes-service
        run: |
          docker build -t tynaz02/notes-service:version2 .

      - name: List Docker images
        run: docker images

  build-etudiants-service:
    runs-on: ubuntu-latest
    name: Build etudiants-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (etudiants-service)
        working-directory: backend/etudiants-service
        run: |

          docker build -t tynaz02/etudiants-service:version2 .

      - name: List Docker images
        run: docker images
